package parts

import (
	"encoding/xml"
	"fmt"
	"io"
	"strconv"
	"strings"
	"sync"

	"github.com/hurtener/pptx-go/opc"
	"github.com/hurtener/pptx-go/utils"
)

// NewShapeIDAllocator creates a new ID allocator.
// reservedID: the reserved starting ID; nextID begins at reservedID + 1.
func NewShapeIDAllocator(reservedID uint32) *ShapeIDAllocator {
	return &ShapeIDAllocator{
		nextID:     reservedID + 1,
		reservedID: reservedID,
		maxID:      0, // no limit
	}
}

// NewShapeIDAllocatorWithMax creates an allocator with a maximum ID limit.
func NewShapeIDAllocatorWithMax(reservedID, maxID uint32) *ShapeIDAllocator {
	return &ShapeIDAllocator{
		nextID:     reservedID + 1,
		reservedID: reservedID,
		maxID:      maxID,
	}
}

// Next allocates the next ID and returns it.
func (a *ShapeIDAllocator) Next() uint32 {
	if a.maxID > 0 && a.nextID >= a.maxID {
		return 0 // out of range
	}
	id := a.nextID
	a.nextID++
	return id
}

// NextBatch allocates count IDs in bulk and returns them (does not include reservedID).
func (a *ShapeIDAllocator) NextBatch(count int) []uint32 {
	ids := make([]uint32, count)
	for i := 0; i < count; i++ {
		ids[i] = a.Next()
	}
	return ids
}

// Peek returns the next ID that would be allocated without actually allocating it.
func (a *ShapeIDAllocator) Peek() uint32 {
	return a.nextID
}

// Current returns the most recently allocated ID.
func (a *ShapeIDAllocator) Current() uint32 {
	if a.nextID > a.reservedID+1 {
		return a.nextID - 1
	}
	return a.reservedID
}

// Reset resets the allocator to start from reservedID + 1.
func (a *ShapeIDAllocator) Reset() {
	a.nextID = a.reservedID + 1
}

// ResetFrom resets the allocator to start from startID.
func (a *ShapeIDAllocator) ResetFrom(startID uint32) {
	a.nextID = startID
}

// SetReserved sets the reserved starting ID and resets the allocator.
func (a *ShapeIDAllocator) SetReserved(reservedID uint32) {
	a.reservedID = reservedID
	a.nextID = reservedID + 1
}

// Remaining returns the number of IDs still available for allocation.
func (a *ShapeIDAllocator) Remaining() uint32 {
	if a.maxID == 0 {
		return ^uint32(0) // maximum value
	}
	return a.maxID - a.nextID + 1
}

// IsExhausted reports whether the allocator has run out of IDs.
func (a *ShapeIDAllocator) IsExhausted() bool {
	if a.maxID == 0 {
		return false
	}
	return a.nextID > a.maxID
}

// UsedCount returns the number of IDs that have been allocated.
func (a *ShapeIDAllocator) UsedCount() uint32 {
	return a.nextID - a.reservedID - 1
}

// ============================================================================
// NewShapeIDAllocatorSync creates a thread-safe ID allocator.
func NewShapeIDAllocatorSync(reservedID uint32) *ShapeIDAllocatorSync {
	return &ShapeIDAllocatorSync{
		nextID:     reservedID + 1,
		reservedID: reservedID,
	}
}

// NewShapeIDAllocatorSyncWithMax creates a thread-safe allocator with a maximum ID limit.
func NewShapeIDAllocatorSyncWithMax(reservedID, maxID uint32) *ShapeIDAllocatorSync {
	return &ShapeIDAllocatorSync{
		nextID:     reservedID + 1,
		reservedID: reservedID,
		maxID:      maxID,
	}
}

// Next allocates the next ID in a thread-safe manner.
func (a *ShapeIDAllocatorSync) Next() uint32 {
	a.mu.Lock()
	defer a.mu.Unlock()

	if a.maxID > 0 && a.nextID >= a.maxID {
		return 0
	}
	id := a.nextID
	a.nextID++
	return id
}

// NextBatch allocates count IDs in bulk in a thread-safe manner.
func (a *ShapeIDAllocatorSync) NextBatch(count int) []uint32 {
	a.mu.Lock()
	defer a.mu.Unlock()

	ids := make([]uint32, count)
	for i := 0; i < count; i++ {
		if a.maxID > 0 && a.nextID >= a.maxID {
			ids[i] = 0
			continue
		}
		ids[i] = a.nextID
		a.nextID++
	}
	return ids
}

// TryNext tries to allocate an ID; returns false if no IDs are available.
func (a *ShapeIDAllocatorSync) TryNext() (uint32, bool) {
	a.mu.Lock()
	defer a.mu.Unlock()

	if a.maxID > 0 && a.nextID >= a.maxID {
		return 0, false
	}
	id := a.nextID
	a.nextID++
	return id, true
}

// Peek returns the next ID that would be allocated, without allocating it, in a thread-safe manner.
func (a *ShapeIDAllocatorSync) Peek() uint32 {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.nextID
}

// Reset resets the allocator in a thread-safe manner.
func (a *ShapeIDAllocatorSync) Reset() {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.nextID = a.reservedID + 1
}

// ResetFrom resets the allocator to start from startID in a thread-safe manner.
func (a *ShapeIDAllocatorSync) ResetFrom(startID uint32) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.nextID = startID
}

// ============================================================================
// SlidePart ID management methods
// ============================================================================

// Allocator returns the current shape ID allocator for custom management.
// Note: a single Slide is generated by a single goroutine and is not concurrent-safe.
func (s *SlidePart) Allocator() *ShapeIDAllocator {
	return &ShapeIDAllocator{
		nextID:     s.nextShapeID,
		reservedID: 1,
	}
}

// NextShapeID returns the next available shape ID without incrementing the counter.
func (s *SlidePart) NextShapeID() uint32 {
	return s.nextShapeID
}

// AllocateShapeID allocates a new shape ID and returns it.
func (s *SlidePart) AllocateShapeID() uint32 {
	id := s.nextShapeID
	s.nextShapeID++
	return id
}

// AllocateShapeIDBatch allocates count shape IDs in bulk.
func (s *SlidePart) AllocateShapeIDBatch(count int) []uint32 {
	ids := make([]uint32, count)
	for i := 0; i < count; i++ {
		ids[i] = s.nextShapeID
		s.nextShapeID++
	}
	return ids
}

// AllocateShapeIDWithOffset allocates a shape ID offset by the given amount above the current position.
func (s *SlidePart) AllocateShapeIDWithOffset(offset uint32) uint32 {
	id := s.nextShapeID + offset
	s.nextShapeID = id + 1
	return id
}

// PeekNextShapeID returns the next available shape ID without incrementing the counter.
func (s *SlidePart) PeekNextShapeID() uint32 {
	return s.nextShapeID
}

// CurrentShapeID returns the most recently allocated shape ID.
func (s *SlidePart) CurrentShapeID() uint32 {
	if s.nextShapeID > 2 {
		return s.nextShapeID - 1
	}
	return 1
}

// ResetShapeID resets the shape ID allocator.
func (s *SlidePart) ResetShapeID() {
	s.nextShapeID = 2
}

// SetShapeIDStart sets the starting value for shape ID allocation.
func (s *SlidePart) SetShapeIDStart(startID uint32) {
	if startID < 2 {
		startID = 2
	}
	s.nextShapeID = startID
}

// ShapeIDCount returns the number of shape IDs that have been allocated.
func (s *SlidePart) ShapeIDCount() uint32 {
	return s.nextShapeID - 2
}

// NewSlidePart creates a new slide part.
func NewSlidePart(id int) *SlidePart {
	uri := opc.NewPackURI(fmt.Sprintf("/ppt/slides/slide%d.xml", id))
	return &SlidePart{
		uri:         uri,
		spTree:      NewXSpTree(),
		nextShapeID: 2, // 1 is already used by the spTree itself
		rels:        opc.NewRelationships(uri),
	}
}

// NewSlidePartWithURI creates a slide part with the specified URI.
func NewSlidePartWithURI(uri *opc.PackURI) *SlidePart {
	return &SlidePart{
		uri:         uri,
		spTree:      NewXSpTree(),
		nextShapeID: 2,
		rels:        opc.NewRelationships(uri),
	}
}

// PartURI returns the part URI.
func (s *SlidePart) PartURI() *opc.PackURI {
	return s.uri
}

// SetURI sets the part URI.
func (s *SlidePart) SetURI(uri *opc.PackURI) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.uri = uri
}

// LayoutRId returns the associated layout relationship ID.
func (s *SlidePart) LayoutRId() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.layoutRId
}

// SetLayoutRId sets the associated layout relationship ID.
func (s *SlidePart) SetLayoutRId(rId string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.layoutRId = rId
}

// MasterRId returns the associated master relationship ID.
func (s *SlidePart) MasterRId() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.masterRId
}

// SetMasterRId sets the associated master relationship ID.
func (s *SlidePart) SetMasterRId(rId string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.masterRId = rId
}

// Relationships returns the slide relationship manager (using opc.Relationships).
func (s *SlidePart) Relationships() *opc.Relationships {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.rels
}

// SpTree returns the shape tree for use by upper-layer builder operations.
func (s *SlidePart) SpTree() *XSpTree {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.spTree
}

// AppendShapeChild appends a child element to the shape tree for upper-layer builder operations.
func (s *SlidePart) AppendShapeChild(child any) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.spTree.Children = append(s.spTree.Children, child)
}

// NewXSpTree creates a new shape tree.
func NewXSpTree() *XSpTree {
	return &XSpTree{
		NonVisual: nvGrpSpPr{
			CNvPr: &XNvCxnSpPr{
				ID:   1,
				Name: "Layout",
			},
		},
		Children: make([]any, 0),
	}
}

// ToXML serializes the SlidePart to XML using the shared XMLWriterPool.
func (s *SlidePart) ToXML() ([]byte, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	xs := XSlide{
		XmlnsA: "http://schemas.openxmlformats.org/drawingml/2006/main",
		XmlnsR: "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
		XmlnsP: "http://schemas.openxmlformats.org/presentationml/2006/main",
		ClrMapOvr: &XClrMapOvr{
			Accent1: "accent1",
		},
		CSld: &XCSld{
			SpTree: s.spTree,
		},
	}

	// Serialize using the shared XMLWriterPool.
	xw := globalXMLWriterPool.Get()
	defer globalXMLWriterPool.Put(xw)

	xw.ResetBuffer()
	if err := xw.Declaration(); err != nil {
		return nil, err
	}
	if err := xs.WriteXML(xw); err != nil {
		return nil, err
	}
	return xw.Bytes(), nil
}

// FromXML deserializes a SlidePart from XML.
func (s *SlidePart) FromXML(data []byte) error {
	// Strip namespace prefixes for compatibility with Go's xml.Unmarshal.
	cleanData, err := StripNamespacePrefixes(data)
	if err != nil {
		return fmt.Errorf("failed to clean XML: %w", err)
	}

	var xs XSlide
	if err := xml.Unmarshal(cleanData, &xs); err != nil {
		return fmt.Errorf("failed to unmarshal slide XML: %w", err)
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	if xs.CSld != nil && xs.CSld.SpTree != nil {
		s.spTree = xs.CSld.SpTree
	}

	return nil
}

// NewSlideLayoutPart creates a new slide layout part.
func NewSlideLayoutPart(id int) *SlideLayoutPart {
	return &SlideLayoutPart{
		uri:        opc.NewPackURI(fmt.Sprintf("/ppt/slideLayouts/slideLayout%d.xml", id)),
		spTree:     NewXSpTree(),
		layoutType: SlideLayoutBlank,
	}
}

// PartURI returns the part URI.
func (s *SlideLayoutPart) PartURI() *opc.PackURI {
	return s.uri
}

// LayoutType returns the layout type.
func (s *SlideLayoutPart) LayoutType() SlideLayoutType {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.layoutType
}

// SetLayoutType sets the layout type.
func (s *SlideLayoutPart) SetLayoutType(t SlideLayoutType) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.layoutType = t
}

// MasterRId returns the associated master relationship ID.
func (s *SlideLayoutPart) MasterRId() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.masterRId
}

// SetMasterRId sets the associated master relationship ID.
func (s *SlideLayoutPart) SetMasterRId(rId string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.masterRId = rId
}

// AddImageRel adds an image relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddImageRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check: reuse the existing rId if a relationship with the same target already exists.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	// Create a new relationship.
	rel, err := s.rels.AddNew(RelTypeImage, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}

// AddMediaRel adds a media relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddMediaRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	rel, err := s.rels.AddNew(RelTypeMedia, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}

// AddChartRel adds a chart relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddChartRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	rel, err := s.rels.AddNew(RelTypeChart, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}

// AddTableRel adds a table relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddTableRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	rel, err := s.rels.AddNew(RelTypeTable, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}

// NewXMLWriter creates a new XMLWriter.
func NewXMLWriter(w io.Writer) *XMLWriter {
	return &XMLWriter{
		w:          w,
		buf:        make([]byte, 0, 4096),
		indent:     0,
		indentStr:  "  ",
		useIndent:  true,
		autoFlush:  false,
		nsPrefixes: make(map[string]string),
	}
}

// NewXMLWriterWithIndent creates an XMLWriter with the given indent string.
func NewXMLWriterWithIndent(w io.Writer, indentStr string) *XMLWriter {
	return &XMLWriter{
		w:          w,
		buf:        make([]byte, 0, 4096),
		indent:     0,
		indentStr:  indentStr,
		useIndent:  true,
		autoFlush:  false,
		nsPrefixes: make(map[string]string),
	}
}

// NewXMLWriterBuffered creates a buffered XMLWriter with the given initial capacity.
func NewXMLWriterBuffered(cap int) *XMLWriter {
	return &XMLWriter{
		w:          nil,
		buf:        make([]byte, 0, cap),
		indent:     0,
		indentStr:  "  ",
		useIndent:  true,
		autoFlush:  false,
		nsPrefixes: make(map[string]string),
	}
}

// SetAutoFlush enables or disables automatic flushing to the underlying writer.
func (xw *XMLWriter) SetAutoFlush(enable bool) {
	xw.autoFlush = enable
}

// SetIndent sets the indent string.
func (xw *XMLWriter) SetIndent(indentStr string) {
	xw.indentStr = indentStr
}

// SetUseIndent enables or disables indentation.
func (xw *XMLWriter) SetUseIndent(use bool) {
	xw.useIndent = use
}

// writeRaw writes bytes directly to the buffer.
func (xw *XMLWriter) writeRaw(data []byte) error {
	xw.buf = append(xw.buf, data...)
	if xw.autoFlush && xw.w != nil {
		_, err := xw.w.Write(xw.buf)
		xw.buf = xw.buf[:0]
		return err
	}
	return nil
}

// writeIndent writes the current indentation.
func (xw *XMLWriter) writeIndent() error {
	if xw.useIndent {
		for i := 0; i < xw.indent; i++ {
			if err := xw.writeRaw([]byte(xw.indentStr)); err != nil {
				return err
			}
		}
	}
	return nil
}

// Declaration writes the XML declaration.
func (xw *XMLWriter) Declaration() error {
	return xw.writeRaw([]byte(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`))
}

// DeclarationWithEncoding writes an XML declaration with the specified encoding.
func (xw *XMLWriter) DeclarationWithEncoding(encoding string) error {
	return xw.writeRaw([]byte(`<?xml version="1.0" encoding="` + encoding + `" standalone="yes"?>`))
}

// StartElement writes an opening element tag.
func (xw *XMLWriter) StartElement(prefix, localName string) error {
	if prefix != "" {
		return xw.writeRaw([]byte("<" + prefix + ":" + localName + ">"))
	}
	return xw.writeRaw([]byte("<" + localName + ">"))
}

// StartElementNS writes an opening element tag with a namespace declaration.
func (xw *XMLWriter) StartElementNS(prefix, localName, ns string) error {
	xw.nsPrefixes[ns] = prefix
	if prefix != "" {
		return xw.writeRaw([]byte("<" + prefix + ":" + localName + " xmlns:" + prefix + "=\"" + ns + "\">"))
	}
	return xw.writeRaw([]byte("<" + localName + " xmlns=\"" + ns + "\">"))
}

// StartElementWithAttrs writes an opening element tag with attributes.
func (xw *XMLWriter) StartElementWithAttrs(prefix, localName string, attrs ...string) error {
	tag := "<"
	if prefix != "" {
		tag += prefix + ":" + localName
	} else {
		tag += localName
	}
	for i := 0; i < len(attrs); i += 2 {
		if i+1 < len(attrs) {
			tag += " " + attrs[i] + "=\"" + xw.escapeAttr(attrs[i+1]) + "\""
		}
	}
	tag += ">"
	return xw.writeRaw([]byte(tag))
}

// StartElementNSWithAttrs writes an opening element tag with a namespace declaration and attributes.
func (xw *XMLWriter) StartElementNSWithAttrs(prefix, localName, ns string, attrs ...string) error {
	xw.nsPrefixes[ns] = prefix
	tag := "<"
	if prefix != "" {
		tag += prefix + ":" + localName + " xmlns:" + prefix + "=\"" + ns + "\""
	} else {
		tag += localName + " xmlns=\"" + ns + "\""
	}
	for i := 0; i < len(attrs); i += 2 {
		if i+1 < len(attrs) {
			tag += " " + attrs[i] + "=\"" + xw.escapeAttr(attrs[i+1]) + "\""
		}
	}
	tag += ">"
	return xw.writeRaw([]byte(tag))
}

// StartElementRaw writes an opening element tag without escaping attribute values.
func (xw *XMLWriter) StartElementRaw(prefix, localName string, attrs ...string) error {
	tag := "<"
	if prefix != "" {
		tag += prefix + ":" + localName
	} else {
		tag += localName
	}
	for i := 0; i < len(attrs); i += 2 {
		if i+1 < len(attrs) {
			tag += " " + attrs[i] + "=\"" + attrs[i+1] + "\""
		}
	}
	tag += ">"
	return xw.writeRaw([]byte(tag))
}

// EndElement writes a closing element tag.
func (xw *XMLWriter) EndElement(prefix, localName string) error {
	if prefix != "" {
		return xw.writeRaw([]byte("</" + prefix + ":" + localName + ">"))
	}
	return xw.writeRaw([]byte("</" + localName + ">"))
}

// EmptyElement writes a self-closing element tag.
func (xw *XMLWriter) EmptyElement(prefix, localName string) error {
	if prefix != "" {
		return xw.writeRaw([]byte("<" + prefix + ":" + localName + "/>"))
	}
	return xw.writeRaw([]byte("<" + localName + "/>"))
}

// EmptyElementWithAttrs writes a self-closing element tag with attributes.
func (xw *XMLWriter) EmptyElementWithAttrs(prefix, localName string, attrs ...string) error {
	tag := "<"
	if prefix != "" {
		tag += prefix + ":" + localName
	} else {
		tag += localName
	}
	for i := 0; i < len(attrs); i += 2 {
		if i+1 < len(attrs) {
			tag += " " + attrs[i] + "=\"" + xw.escapeAttr(attrs[i+1]) + "\""
		}
	}
	tag += "/>"
	return xw.writeRaw([]byte(tag))
}

// Text writes escaped text content.
func (xw *XMLWriter) Text(content string) error {
	return xw.writeRaw([]byte(xw.escapeText(content)))
}

// TextRaw writes raw text without escaping.
func (xw *XMLWriter) TextRaw(content string) error {
	return xw.writeRaw([]byte(content))
}

// CharData writes escaped character data.
func (xw *XMLWriter) CharData(data []byte) error {
	return xw.writeRaw([]byte(xw.escapeText(string(data))))
}

// Comment writes an XML comment.
func (xw *XMLWriter) Comment(content string) error {
	if err := xw.writeRaw([]byte("<!--")); err != nil {
		return err
	}
	if err := xw.writeRaw([]byte(content)); err != nil {
		return err
	}
	return xw.writeRaw([]byte("-->"))
}

// CData writes a CDATA section.
func (xw *XMLWriter) CData(content string) error {
	if err := xw.writeRaw([]byte("<![CDATA[")); err != nil {
		return err
	}
	if err := xw.writeRaw([]byte(content)); err != nil {
		return err
	}
	return xw.writeRaw([]byte("]]>"))
}

// ProcessingInstruction writes a processing instruction.
func (xw *XMLWriter) ProcessingInstruction(target, data string) error {
	if data != "" {
		return xw.writeRaw([]byte("<?" + target + " " + data + "?>"))
	}
	return xw.writeRaw([]byte("<?" + target + "?>"))
}

// Indent increases the indentation level.
func (xw *XMLWriter) Indent() {
	xw.indent++
}

// Dedent decreases the indentation level.
func (xw *XMLWriter) Dedent() {
	if xw.indent > 0 {
		xw.indent--
	}
}

// WithIndent temporarily increases the indentation level, then restores it after fn returns.
func (xw *XMLWriter) WithIndent(fn func()) {
	xw.Indent()
	fn()
	xw.Dedent()
}

// Newline writes a newline character.
func (xw *XMLWriter) Newline() error {
	return xw.writeRaw([]byte{'\n'})
}

// Raw writes raw content directly to the buffer.
func (xw *XMLWriter) Raw(content string) error {
	return xw.writeRaw([]byte(content))
}

// Flush writes the buffered content to the underlying writer.
func (xw *XMLWriter) Flush() error {
	if xw.w == nil {
		return fmt.Errorf("XMLWriter: writer is nil, no io.Writer configured")
	}
	_, err := xw.w.Write(xw.buf)
	xw.buf = xw.buf[:0]
	return err
}

// Bytes returns a copy of the buffer contents.
// A copy is required because the XMLWriter is pooled and reused; returning a
// slice reference would cause a data race when the writer is returned to the pool.
func (xw *XMLWriter) Bytes() []byte {
	// Create a copy to avoid race conditions.
	result := make([]byte, len(xw.buf))
	copy(result, xw.buf)
	return result
}

// String returns the buffer contents as a string.
func (xw *XMLWriter) String() string {
	return string(xw.buf)
}

// Reset resets the writer and sets the underlying io.Writer.
func (xw *XMLWriter) Reset(w io.Writer) {
	xw.w = w
	xw.buf = xw.buf[:0]
	xw.indent = 0
	xw.nsPrefixes = make(map[string]string)
}

// ResetBuffer clears the internal buffer.
func (xw *XMLWriter) ResetBuffer() {
	xw.buf = xw.buf[:0]
}

// Size returns the current size of the buffer.
func (xw *XMLWriter) Size() int {
	return len(xw.buf)
}

// Capacity returns the current capacity of the buffer.
func (xw *XMLWriter) Capacity() int {
	return cap(xw.buf)
}

// escapeText escapes XML text content.
func (xw *XMLWriter) escapeText(s string) string {
	// Quick check: if no special characters, return as-is.
	if !strings.ContainsAny(s, "<>&\"'") {
		return s
	}

	var sb strings.Builder
	sb.Grow(len(s) + 16)
	for _, r := range s {
		switch r {
		case '<':
			sb.WriteString("&lt;")
		case '>':
			sb.WriteString("&gt;")
		case '&':
			sb.WriteString("&amp;")
		case '"':
			sb.WriteString("&quot;")
		case '\'':
			sb.WriteString("&apos;")
		default:
			sb.WriteRune(r)
		}
	}
	return sb.String()
}

// escapeAttr escapes XML attribute values.
func (xw *XMLWriter) escapeAttr(s string) string {
	// Quick check: if no special characters, return as-is.
	if !strings.ContainsAny(s, "<>&\"'") {
		return s
	}

	var sb strings.Builder
	sb.Grow(len(s) + 16)
	for _, r := range s {
		switch r {
		case '<':
			sb.WriteString("&lt;")
		case '>':
			sb.WriteString("&gt;")
		case '&':
			sb.WriteString("&amp;")
		case '"':
			sb.WriteString("&quot;")
		case '\'':
			sb.WriteString("&apos;")
		default:
			sb.WriteRune(r)
		}
	}
	return sb.String()
}

// WriteInt writes an integer value.
func (xw *XMLWriter) WriteInt(val int) error {
	return xw.writeRaw([]byte(strconv.Itoa(val)))
}

// WriteInt64 writes a 64-bit integer value.
func (xw *XMLWriter) WriteInt64(val int64) error {
	return xw.writeRaw([]byte(strconv.FormatInt(val, 10)))
}

// WriteUint64 writes an unsigned 64-bit integer value.
func (xw *XMLWriter) WriteUint64(val uint64) error {
	return xw.writeRaw([]byte(strconv.FormatUint(val, 10)))
}

// WriteFloat64 writes a float64 value with the given precision.
func (xw *XMLWriter) WriteFloat64(val float64, prec int) error {
	return xw.writeRaw([]byte(strconv.FormatFloat(val, 'f', prec, 64)))
}

// WriteBool writes a boolean value as "1" or "0".
func (xw *XMLWriter) WriteBool(val bool) error {
	if val {
		return xw.writeRaw([]byte("1"))
	}
	return xw.writeRaw([]byte("0"))
}

// WriteBoolStr writes a boolean value as "true" or "false".
func (xw *XMLWriter) WriteBoolStr(val bool) error {
	if val {
		return xw.writeRaw([]byte("true"))
	}
	return xw.writeRaw([]byte("false"))
}

// WriteEMUs writes an EMU (English Metric Unit) value used for PowerPoint dimensions.
func (xw *XMLWriter) WriteEMUs(val int64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(val)))
}

// WriteEMUsWithUnit writes an EMU value.
func (xw *XMLWriter) WriteEMUsWithUnit(val int64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(val)))
}

// WriteEMUsF writes a float64 value converted to EMU.
func (xw *XMLWriter) WriteEMUsF(val float64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(int64(val))))
}

// WriteInchesAsEMU converts inches to EMU and writes the value.
func (xw *XMLWriter) WriteInchesAsEMU(inches float64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(utils.InchesToEMU(inches))))
}

// WriteCentimetersAsEMU converts centimeters to EMU and writes the value.
func (xw *XMLWriter) WriteCentimetersAsEMU(cm float64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(utils.CentimetersToEMU(cm))))
}

// WriteMillimetersAsEMU converts millimeters to EMU and writes the value.
func (xw *XMLWriter) WriteMillimetersAsEMU(mm float64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(utils.MillimetersToEMU(mm))))
}

// WritePointsAsEMU converts points to EMU and writes the value.
func (xw *XMLWriter) WritePointsAsEMU(points float64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(utils.PointsToEMU(points))))
}

// WritePixelsAsEMU converts pixels to EMU and writes the value.
func (xw *XMLWriter) WritePixelsAsEMU(pixels float64) error {
	return xw.writeRaw([]byte(utils.WriteEMUAttr(utils.PixelsToEMU(pixels))))
}

// WritePercentage writes a percentage value.
func (xw *XMLWriter) WritePercentage(val int) error {
	return xw.writeRaw([]byte(strconv.Itoa(val)))
}

// NewXMLWriterPool creates a new XMLWriterPool.
func NewXMLWriterPool() *XMLWriterPool {
	return &XMLWriterPool{
		pool: sync.Pool{
			New: func() any {
				return &XMLWriter{
					buf:        make([]byte, 0, 4096),
					indent:     0,
					indentStr:  "  ",
					useIndent:  true,
					autoFlush:  false,
					nsPrefixes: make(map[string]string),
				}
			},
		},
	}
}

// globalXMLWriterPool is the global XMLWriter pool used as the shared serialization base.
var globalXMLWriterPool = NewXMLWriterPool()

// Get retrieves or creates an XMLWriter from the pool.
func (p *XMLWriterPool) Get() *XMLWriter {
	xw := p.pool.Get().(*XMLWriter)
	xw.buf = xw.buf[:0]
	xw.indent = 0
	xw.nsPrefixes = make(map[string]string)
	return xw
}

// Put returns an XMLWriter to the pool.
func (p *XMLWriterPool) Put(xw *XMLWriter) {
	xw.w = nil
	xw.buf = xw.buf[:0]
	xw.autoFlush = false
	xw.nsPrefixes = make(map[string]string)
	p.pool.Put(xw)
}

// GetWithWriter retrieves an XMLWriter from the pool and configures it with the given writer.
func (p *XMLWriterPool) GetWithWriter(w io.Writer) *XMLWriter {
	xw := p.Get()
	xw.w = w
	return xw
}

// GetBuffered retrieves a buffered XMLWriter from the pool.
func (p *XMLWriterPool) GetBuffered() *XMLWriter {
	return p.Get()
}

// ============================================================================
// WriteXML methods for XML structs
// ============================================================================

// WriteXML serializes XSlide to XML.
func (xs *XSlide) WriteXML(xw *XMLWriter) error {
	// Write p:sld opening tag with namespace declarations.
	if err := xw.StartElementWithAttrs("p", "sld",
		"xmlns:a", "http://schemas.openxmlformats.org/drawingml/2006/main",
		"xmlns:r", "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
		"xmlns:p", "http://schemas.openxmlformats.org/presentationml/2006/main",
	); err != nil {
		return err
	}

	// Write color map override.
	if err := xw.StartElement("p", "clrMapOvr"); err != nil {
		return err
	}
	if err := xw.EmptyElementWithAttrs("a", "defRgbClrModel", "val", "bg1"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "clrMapOvr"); err != nil {
		return err
	}

	// Write shape tree.
	if xs.CSld != nil && xs.CSld.SpTree != nil {
		if err := xs.CSld.SpTree.WriteXML(xw); err != nil {
			return err
		}
	}

	return xw.EndElement("p", "sld")
}

// WriteXML serializes XSpTree to XML.
func (xst *XSpTree) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("p", "spTree"); err != nil {
		return err
	}

	// Write non-visual group shape properties.
	if err := xw.StartElement("p", "nvGrpSpPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.WriteInt(xst.NonVisual.CNvPr.ID); err != nil {
		return err
	}
	if xst.NonVisual.CNvPr.Name != "" {
		if err := xw.Raw(" name=\"" + xst.NonVisual.CNvPr.Name + "\""); err != nil {
			return err
		}
	}
	if err := xw.EndElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvGrpSpPr"); err != nil {
		return err
	}
	if err := xw.EmptyElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "cNvGrpSpPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "nvGrpSpPr"); err != nil {
		return err
	}

	// Write group shape properties.
	if xst.GroupShapeProperties != nil && xst.GroupShapeProperties.Xfrm != nil {
		if err := xst.GroupShapeProperties.Xfrm.WriteXML(xw); err != nil {
			return err
		}
	}

	// Write children.
	for _, child := range xst.Children {
		switch v := child.(type) {
		case *XSp:
			if err := v.WriteXML(xw); err != nil {
				return err
			}
		case *XPicture:
			if err := v.WriteXML(xw); err != nil {
				return err
			}
		case *XGraphicFrame:
			if err := v.WriteXML(xw); err != nil {
				return err
			}
		}
	}

	return xw.EndElement("p", "spTree")
}

// WriteXML serializes XTransform2D to XML.
func (xt *XTransform2D) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("a", "xfrm"); err != nil {
		return err
	}

	// Write offset.
	if xt.Offset != nil {
		if err := xw.EmptyElementWithAttrs("a", "off", "x", strconv.Itoa(xt.Offset.X), "y", strconv.Itoa(xt.Offset.Y)); err != nil {
			return err
		}
	}

	// Write extent.
	if xt.Extent != nil {
		if err := xw.EmptyElementWithAttrs("a", "ext", "cx", strconv.Itoa(xt.Extent.Cx), "cy", strconv.Itoa(xt.Extent.Cy)); err != nil {
			return err
		}
	}

	// Write rotation angle.
	if xt.Rotation != 0 {
		if err := xw.Raw(" rot=\"" + strconv.Itoa(xt.Rotation) + "\""); err != nil {
			return err
		}
	}

	return xw.EndElement("a", "xfrm")
}

// WriteXML serializes XShapeProperties to XML.
func (xsp *XShapeProperties) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("p", "spPr"); err != nil {
		return err
	}

	// Write transform.
	if xsp.Transform2D != nil {
		if err := xsp.Transform2D.WriteXML(xw); err != nil {
			return err
		}
	}

	// Write fill.
	if xsp.PresetFill != nil {
		if err := xw.StartElement("a", "solidFill"); err != nil {
			return err
		}
		if xsp.PresetFill.SrgbClr != nil {
			if err := xw.EmptyElementWithAttrs("a", "srgbClr", "val", xsp.PresetFill.SrgbClr.Val); err != nil {
				return err
			}
		} else if xsp.PresetFill.SchemeClr != nil {
			if err := xw.EmptyElementWithAttrs("a", "schemeClr", "val", xsp.PresetFill.SchemeClr.Val); err != nil {
				return err
			}
		}
		if err := xw.EndElement("a", "solidFill"); err != nil {
			return err
		}
	}

	// Write line.
	if xsp.Line != nil {
		if err := xw.StartElement("a", "ln"); err != nil {
			return err
		}
		if xsp.Line.Width != 0 {
			if err := xw.Raw(" w=\"" + strconv.Itoa(xsp.Line.Width) + "\""); err != nil {
				return err
			}
		}
		if xsp.Line.SolidFill != nil {
			if err := xw.StartElement("a", "solidFill"); err != nil {
				return err
			}
			if xsp.Line.SolidFill.SrgbClr != nil {
				if err := xw.EmptyElementWithAttrs("a", "srgbClr", "val", xsp.Line.SolidFill.SrgbClr.Val); err != nil {
					return err
				}
			}
			if err := xw.EndElement("a", "solidFill"); err != nil {
				return err
			}
		}
		if err := xw.EndElement("a", "ln"); err != nil {
			return err
		}
	}

	return xw.EndElement("p", "spPr")
}

// WriteXML serializes XSp to XML.
func (xs *XSp) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("p", "sp"); err != nil {
		return err
	}

	// Write non-visual properties.
	if err := xw.StartElement("p", "nvSpPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.WriteInt(xs.NonVisual.CNvPr.ID); err != nil {
		return err
	}
	if xs.NonVisual.CNvPr.Name != "" {
		if err := xw.Raw(" name=\"" + xs.NonVisual.CNvPr.Name + "\""); err != nil {
			return err
		}
	}
	if err := xw.EndElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvSpPr"); err != nil {
		return err
	}
	if err := xw.EmptyElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "cNvSpPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "nvSpPr"); err != nil {
		return err
	}

	// Write shape properties.
	if xs.ShapeProperties != nil {
		if err := xs.ShapeProperties.WriteXML(xw); err != nil {
			return err
		}
	}

	// Write text body.
	if xs.TextBody != nil {
		if err := xs.TextBody.WriteXML(xw); err != nil {
			return err
		}
	}

	return xw.EndElement("p", "sp")
}

// WriteXML serializes XTextBody to XML.
func (xtb *XTextBody) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("p", "txBody"); err != nil {
		return err
	}

	// Write body properties.
	if err := xw.StartElement("a", "bodyPr"); err != nil {
		return err
	}
	if xtb.BodyPr != nil {
		if xtb.BodyPr.Wrap != "" {
			if err := xw.Raw(" wrap=\"" + xtb.BodyPr.Wrap + "\""); err != nil {
				return err
			}
		}
		if xtb.BodyPr.Rotation != 0 {
			if err := xw.Raw(" rot=\"" + strconv.Itoa(xtb.BodyPr.Rotation) + "\""); err != nil {
				return err
			}
		}
		if xtb.BodyPr.Vertical != "" {
			if err := xw.Raw(" vert=\"" + xtb.BodyPr.Vertical + "\""); err != nil {
				return err
			}
		}
		if xtb.BodyPr.Anchor != "" {
			if err := xw.Raw(" anchor=\"" + xtb.BodyPr.Anchor + "\""); err != nil {
				return err
			}
		}
	}
	if err := xw.EndElement("a", "bodyPr"); err != nil {
		return err
	}

	// Write list style.
	if xtb.LstStyle != nil {
		if err := xw.EmptyElement("a", "lstStyle"); err != nil {
			return err
		}
	}

	// Write paragraphs.
	for _, para := range xtb.Paragraphs {
		if err := para.WriteXML(xw); err != nil {
			return err
		}
	}

	return xw.EndElement("p", "txBody")
}

// WriteXML serializes XTextParagraph to XML.
func (xtp *XTextParagraph) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("a", "p"); err != nil {
		return err
	}

	// Write paragraph properties.
	if xtp.Level != 0 {
		if err := xw.Raw(" lvl=\"" + strconv.Itoa(xtp.Level) + "\""); err != nil {
			return err
		}
	}
	if xtp.Indent != 0 {
		if err := xw.Raw(" indent=\"" + strconv.Itoa(xtp.Indent) + "\""); err != nil {
			return err
		}
	}
	if xtp.Alignment != "" {
		if err := xw.Raw(" algn=\"" + xtp.Alignment + "\""); err != nil {
			return err
		}
	}

	// Write text runs.
	for _, run := range xtp.TextRuns {
		if err := run.WriteXML(xw); err != nil {
			return err
		}
	}

	return xw.EndElement("a", "p")
}

// WriteXML serializes XTextRun to XML.
func (xtr *XTextRun) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("a", "r"); err != nil {
		return err
	}

	// Write text properties.
	if xtr.TextProperties != nil {
		if err := xw.StartElement("a", "rPr"); err != nil {
			return err
		}
		props := xtr.TextProperties
		if props.FontSize != 0 {
			if err := xw.Raw(" sz=\"" + strconv.Itoa(props.FontSize) + "\""); err != nil {
				return err
			}
		}
		if props.Bold {
			if err := xw.Raw(" b=\"1\""); err != nil {
				return err
			}
		}
		if props.Italic {
			if err := xw.Raw(" i=\"1\""); err != nil {
				return err
			}
		}
		if props.Underline != "" {
			if err := xw.Raw(" u=\"" + props.Underline + "\""); err != nil {
				return err
			}
		}
		if props.FontFace != "" {
			if err := xw.Raw(" i=\"1\" lang=\"zh-CN\">"); err != nil {
				return err
			}
			if err := xw.EmptyElementWithAttrs("a", "latin", "typeface", props.FontFace); err != nil {
				return err
			}
		}
		if props.Color != "" {
			if err := xw.StartElement("a", "solidFill"); err != nil {
				return err
			}
			if err := xw.EmptyElementWithAttrs("a", "srgbClr", "val", props.Color); err != nil {
				return err
			}
			if err := xw.EndElement("a", "solidFill"); err != nil {
				return err
			}
		}
		if err := xw.EndElement("a", "rPr"); err != nil {
			return err
		}
	}

	// Write text content.
	if err := xw.StartElement("a", "t"); err != nil {
		return err
	}
	if err := xw.Text(xtr.Text); err != nil {
		return err
	}
	if err := xw.EndElement("a", "t"); err != nil {
		return err
	}

	return xw.EndElement("a", "r")
}

// WriteXML serializes XPicture to XML.
func (xp *XPicture) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("p", "pic"); err != nil {
		return err
	}

	// Write non-visual properties.
	if err := xw.StartElement("p", "nvPicPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.WriteInt(xp.NonVisual.CNvPr.ID); err != nil {
		return err
	}
	if xp.NonVisual.CNvPr.Name != "" {
		if err := xw.Raw(" name=\"" + xp.NonVisual.CNvPr.Name + "\""); err != nil {
			return err
		}
	}
	if err := xw.EndElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvPicPr"); err != nil {
		return err
	}
	if err := xw.EmptyElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "cNvPicPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "nvPicPr"); err != nil {
		return err
	}

	// Write blip fill.
	if xp.BlipFill != nil {
		if err := xp.BlipFill.WriteXML(xw); err != nil {
			return err
		}
	}

	// Write shape properties.
	if xp.ShapeProperties != nil {
		if err := xp.ShapeProperties.WriteXML(xw); err != nil {
			return err
		}
	}

	return xw.EndElement("p", "pic")
}

// WriteXML serializes XBlipFillProperties to XML.
func (xbfp *XBlipFillProperties) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("p", "blipFill"); err != nil {
		return err
	}

	// Write blip.
	if xbfp.Blip != nil {
		if err := xw.StartElement("a", "blip"); err != nil {
			return err
		}
		if xbfp.Blip.Embed != "" {
			if err := xw.Raw(" r:embed=\"" + xbfp.Blip.Embed + "\""); err != nil {
				return err
			}
		}
		if err := xw.EndElement("a", "blip"); err != nil {
			return err
		}
	}

	// Write stretch fill.
	if xbfp.Stretch != nil {
		if err := xw.StartElement("a", "stretch"); err != nil {
			return err
		}
		if err := xw.EmptyElement("a", "fillRect"); err != nil {
			return err
		}
		if err := xw.EndElement("a", "stretch"); err != nil {
			return err
		}
	}

	return xw.EndElement("p", "blipFill")
}

// WriteXML serializes XGraphicFrame to XML.
func (xgf *XGraphicFrame) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("p", "graphicFrame"); err != nil {
		return err
	}

	// Write non-visual properties.
	if err := xw.StartElement("p", "nvGraphicFramePr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.WriteInt(xgf.NonVisual.CNvPr.ID); err != nil {
		return err
	}
	if xgf.NonVisual.CNvPr.Name != "" {
		if err := xw.Raw(" name=\"" + xgf.NonVisual.CNvPr.Name + "\""); err != nil {
			return err
		}
	}
	if err := xw.EndElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.StartElement("p", "cNvGraphicFramePr"); err != nil {
		return err
	}
	if err := xw.EmptyElement("p", "cNvPr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "cNvGraphicFramePr"); err != nil {
		return err
	}
	if err := xw.EndElement("p", "nvGraphicFramePr"); err != nil {
		return err
	}

	// Write transform.
	if xgf.Transform2D != nil {
		if err := xgf.Transform2D.WriteXML(xw); err != nil {
			return err
		}
	}

	// Write graphic.
	if xgf.Graphic != nil && xgf.Graphic.Table != nil {
		if err := xw.StartElement("a", "graphic"); err != nil {
			return err
		}
		if err := xgf.Graphic.Table.WriteXML(xw); err != nil {
			return err
		}
		if err := xw.EndElement("a", "graphic"); err != nil {
			return err
		}
	}

	return xw.EndElement("p", "graphicFrame")
}

// WriteXML serializes XTable to XML.
func (xt *XTable) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("a", "graphicData"); err != nil {
		return err
	}
	if err := xw.Raw(" uri=\"http://schemas.openxmlformats.org/drawingml/2006/table\""); err != nil {
		return err
	}

	if err := xw.StartElement("a", "tbl"); err != nil {
		return err
	}

	// Write table grid.
	if err := xw.StartElement("a", "tblGrid"); err != nil {
		return err
	}
	for _, col := range xt.Grid.GridCols {
		if err := xw.EmptyElementWithAttrs("a", "gridCol", "w", strconv.Itoa(col.W)); err != nil {
			return err
		}
	}
	if err := xw.EndElement("a", "tblGrid"); err != nil {
		return err
	}

	// Write rows.
	for _, row := range xt.Rows {
		if err := row.WriteXML(xw); err != nil {
			return err
		}
	}

	if err := xw.EndElement("a", "tbl"); err != nil {
		return err
	}
	if err := xw.EndElement("a", "graphicData"); err != nil {
		return err
	}

	return nil
}

// WriteXML serializes XTableRow to XML.
func (xtr *XTableRow) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("a", "tr"); err != nil {
		return err
	}
	if xtr.GridSpan > 1 {
		if err := xw.Raw(" gridSpan=\"" + strconv.Itoa(xtr.GridSpan) + "\""); err != nil {
			return err
		}
	}

	// Write cells.
	for _, cell := range xtr.Cells {
		if err := cell.WriteXML(xw); err != nil {
			return err
		}
	}

	return xw.EndElement("a", "tr")
}

// WriteXML serializes XTableCell to XML.
func (xtc *XTableCell) WriteXML(xw *XMLWriter) error {
	if err := xw.StartElement("a", "tc"); err != nil {
		return err
	}

	if xtc.GridSpan > 1 {
		if err := xw.Raw(" gridSpan=\"" + strconv.Itoa(xtc.GridSpan) + "\""); err != nil {
			return err
		}
	}
	if xtc.RowSpan > 1 {
		if err := xw.Raw(" rowSpan=\"" + strconv.Itoa(xtc.RowSpan) + "\""); err != nil {
			return err
		}
	}
	if xtc.Vertical != "" {
		if err := xw.Raw(" anchor=\"" + xtc.Vertical + "\""); err != nil {
			return err
		}
	}

	// Write text body.
	if xtc.TextBody != nil {
		if err := xtc.TextBody.WriteXML(xw); err != nil {
			return err
		}
	}

	return xw.EndElement("a", "tc")
}
