package slide

import (
	"sync"

	"github.com/hurtener/pptx-go/internal/opc"
)

// ============================================================================
// SlidePart type definition — corresponds to /ppt/slides/slideN.xml
// ============================================================================

type SlidePart struct {
	uri *opc.PackURI

	// Associated layout relationship ID
	layoutRId string

	// Associated master relationship ID (for quick access)
	masterRId string

	// Slide content
	spTree *XSpTree // shape tree

	// Slide properties
	colorMap *XClrMap // color map
	show     *bool    // whether the slide is shown

	// Local shape ID counter (per-slide, not concurrent-safe;
	// a single slide is generated by a single goroutine).
	nextShapeID uint32

	// Page-level relationship manager (uses the opc-layer implementation)
	rels *opc.Relationships

	mu sync.RWMutex
}

// ============================================================================
// ShapeIDAllocator — single-threaded shape ID allocator
// ============================================================================

// ShapeIDAllocator is a single-threaded shape ID allocator.
// Used to manage ID allocation within a single Slide or ShapeTree.
type ShapeIDAllocator struct {
	nextID     uint32 // next available ID
	reservedID uint32 // reserved starting ID (usually 1, used by the spTree itself)
	maxID      uint32 // maximum ID limit (0 = unlimited)
}

// ============================================================================
// ShapeIDAllocatorSync — thread-safe shape ID allocator
// ============================================================================

// ShapeIDAllocatorSync is a thread-safe shape ID allocator.
// Used for ID allocation in multi-goroutine environments.
type ShapeIDAllocatorSync struct {
	nextID     uint32 // next available ID
	reservedID uint32 // reserved starting ID
	maxID      uint32 // maximum ID limit
	mu         sync.Mutex
}

// ============================================================================
// SlideLayoutPart type definition — corresponds to /ppt/slideLayouts/slideLayoutN.xml
// ============================================================================

// SlideLayoutType enumerates slide layout types.
type SlideLayoutType int

const (
	SlideLayoutBlank             SlideLayoutType = iota // blank layout
	SlideLayoutTitle                                    // title layout
	SlideLayoutTitleAndContent                          // title and content layout
	SlideLayoutTwoContent                               // two-content layout
	SlideLayoutComparison                               // comparison layout
	SlideLayoutTitleOnly                                // title-only layout
	SlideLayoutBlankVertical                            // blank vertical layout
	SlideLayoutObject                                   // object layout
	SlideLayoutPictureAndCaption                        // picture and caption layout
)

// SlideLayoutPart corresponds to /ppt/slideLayouts/slideLayoutN.xml.
type SlideLayoutPart struct {
	uri *opc.PackURI

	layoutType SlideLayoutType

	// Associated master relationship ID
	masterRId string

	// Layout content
	spTree *XSpTree

	mu sync.RWMutex
}

// ============================================================================
// XML struct type definitions
// ============================================================================

// Relationship type constants
const (
	RelationshipTypeImage       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
	RelationshipTypeMedia       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/video"
	RelationshipTypeChart       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart"
	RelationshipTypeSlideLayout = "http://schemas.openxmlformats.org/presentationml/2006/relationships/slideLayout"
	RelationshipTypeSlideMaster = "http://schemas.openxmlformats.org/presentationml/2006/relationships/slideMaster"
	RelationshipTypeTable       = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/table"
)

// XSlide is the XML structure for a slide.
//
// It is serialized with bare (unprefixed) element names via encoding/xml and
// then run through ooxml.RestoreNamespaces, which re-applies the canonical
// p:/a:/r: prefixes and declares the used namespaces on the root (D-032). The
// codec therefore carries no xmlns:* fields — RestoreNamespaces owns them.
type XSlide struct {
	XMLName struct{} `xml:"sld"`

	CSld      *XCSld      `xml:"cSld"`
	ClrMapOvr *XClrMapOvr `xml:"clrMapOvr,omitempty"`
}

// XCSld holds common slide data.
type XCSld struct {
	SpTree *XSpTree `xml:"spTree"`
}

// XClrMap holds the color map.
type XClrMap struct {
	BG1     string `xml:"bg1,attr,omitempty"`
	T1      string `xml:"t1,attr,omitempty"`
	BG2     string `xml:"bg2,attr,omitempty"`
	T2      string `xml:"t2,attr,omitempty"`
	Accent1 string `xml:"accent1,attr,omitempty"`
	Accent2 string `xml:"accent2,attr,omitempty"`
	Accent3 string `xml:"accent3,attr,omitempty"`
	Accent4 string `xml:"accent4,attr,omitempty"`
	Accent5 string `xml:"accent5,attr,omitempty"`
	Accent6 string `xml:"accent6,attr,omitempty"`
	HLink   string `xml:"hlink,attr,omitempty"`
	HLink1  string `xml:"hlink1,attr,omitempty"`
	HLink2  string `xml:"hlink2,attr,omitempty"`
	FollClr string `xml:"follClr,attr,omitempty"`
	LastClr string `xml:"lastClr,attr,omitempty"`
}

// XClrMapOvr holds the color map override. A slide that inherits its master's
// color mapping emits <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>.
type XClrMapOvr struct {
	MasterClrMapping *XMasterClrMapping `xml:"masterClrMapping,omitempty"`
}

// XMasterClrMapping is the empty <a:masterClrMapping/> element signalling that
// the slide uses the master's color map unchanged.
type XMasterClrMapping struct{}

// XSpTree is the shape tree.
type XSpTree struct {
	XMLName struct{} `xml:"spTree"`

	NonVisual            nvGrpSpPr              `xml:"nvGrpSpPr"`
	GroupShapeProperties *XGroupShapeProperties `xml:"grpSpPr,omitempty"`
	Children             []any                  `xml:"-"`
}

// nvGrpSpPr holds non-visual group shape properties.
type nvGrpSpPr struct {
	CNvPr      *XNvCxnSpPr `xml:"cNvPr"`
	CNvGrpSpPr *XNvGrpSpPr `xml:"cNvGrpSpPr"`
}

// XNvCxnSpPr holds non-visual connector shape properties.
type XNvCxnSpPr struct {
	ID   int    `xml:"id,attr"`
	Name string `xml:"name,attr,omitempty"`
}

// XNvGrpSpPr holds non-visual group shape properties.
type XNvGrpSpPr struct {
	CNvPr *XNvPr `xml:"cNvPr,omitempty"`
}

// XNvPr holds non-visual properties.
type XNvPr struct {
	ID   int    `xml:"id,attr,omitempty"`
	Name string `xml:"name,attr,omitempty"`
}

// XGroupShapeProperties holds group shape properties.
type XGroupShapeProperties struct {
	Xfrm *XTransform2D `xml:"xfrm,omitempty"`
}

// XTransform2D represents a 2D transform.
type XTransform2D struct {
	Offset   *XOv2DrOffset `xml:"off,omitempty"`
	Extent   *XOv2DrExtent `xml:"ext,omitempty"`
	Rotation int           `xml:"rot,attr,omitempty"`
	FlipH    bool          `xml:"flipH,attr,omitempty"`
	FlipV    bool          `xml:"flipV,attr,omitempty"`
}

// XOv2DrOffset represents an offset (position).
type XOv2DrOffset struct {
	X int `xml:"x,attr"`
	Y int `xml:"y,attr"`
}

// XOv2DrExtent represents an extent (size).
type XOv2DrExtent struct {
	Cx int `xml:"cx,attr"`
	Cy int `xml:"cy,attr"`
}

// XShapeProperties holds shape properties. Fields are ordered to match the
// CT_ShapeProperties schema: xfrm, geometry, fill, line.
type XShapeProperties struct {
	XMLName     struct{}         `xml:"spPr"`
	Transform2D *XTransform2D    `xml:"xfrm,omitempty"`
	PresetGeom  *XPresetGeometry `xml:"prstGeom,omitempty"`
	SolidFill   *XSolidFill      `xml:"solidFill,omitempty"`
	Line        *XLineProperties `xml:"ln,omitempty"`
}

// XPresetGeometry is a preset shape geometry (<a:prstGeom prst="rect">…</a:prstGeom>).
type XPresetGeometry struct {
	Prst  string  `xml:"prst,attr"`
	AvLst *XAvLst `xml:"avLst"`
}

// XAvLst is the (empty) adjust-value list of a preset geometry.
type XAvLst struct{}

// XSolidFill holds a solid fill color (RGB or scheme).
type XSolidFill struct {
	SrgbClr   *XSrgbClr   `xml:"srgbClr,omitempty"`
	SchemeClr *XSchemeClr `xml:"schemeClr,omitempty"`
}

// XSrgbClr holds an RGB color value.
type XSrgbClr struct {
	Val string `xml:"val,attr"`
}

// XSchemeClr holds a theme color value.
type XSchemeClr struct {
	Val string `xml:"val,attr"`
}

// XLineProperties holds line properties.
type XLineProperties struct {
	Width     int         `xml:"w,attr,omitempty"`
	SolidFill *XSolidFill `xml:"solidFill,omitempty"`
}

// XEmptyElem is a placeholder for required-but-empty OOXML elements (e.g.
// <p:nvPr/>). As a value field (not a pointer) it always serializes, which the
// schema requires for these mandatory children.
type XEmptyElem struct{}

// XSp represents a shape. Field order matches CT_Shape: nvSpPr, spPr, txBody.
type XSp struct {
	XMLName struct{} `xml:"sp"`

	NonVisual       XNonVisualDrawingShape `xml:"nvSpPr"`
	ShapeProperties *XShapeProperties      `xml:"spPr,omitempty"`
	TextBody        *XTextBody             `xml:"txBody,omitempty"`
}

// XNonVisualDrawingShape holds non-visual drawing properties for a shape
// (CT_ShapeNonVisual: cNvPr, cNvSpPr, nvPr).
type XNonVisualDrawingShape struct {
	CNvPr   *XNvCxnSpPr `xml:"cNvPr"`
	CNvSpPr *XNvSpPr    `xml:"cNvSpPr"`
	NvPr    XEmptyElem  `xml:"nvPr"`
}

// XNvSpPr holds non-visual shape properties.
type XNvSpPr struct {
	CNvPr *XNvPr `xml:"cNvPr,omitempty"`
}

// XTextBody holds a text body.
type XTextBody struct {
	XMLName    struct{}            `xml:"txBody"`
	BodyPr     *XBodyPr            `xml:"bodyPr,omitempty"`
	LstStyle   *XTextParagraphList `xml:"lstStyle,omitempty"`
	Paragraphs []XTextParagraph    `xml:"p"`
}

// XBodyPr holds body properties.
type XBodyPr struct {
	Wrap      string `xml:"wrap,attr,omitempty"`
	Rotation  int    `xml:"rot,attr,omitempty"`
	Vertical  string `xml:"vert,attr,omitempty"`
	Anchor    string `xml:"anchor,attr,omitempty"`
	AnchorCtr bool   `xml:"anchorCtr,attr,omitempty"`
}

// XTextParagraphList holds a text paragraph list.
type XTextParagraphList struct {
}

// XTextParagraph represents a text paragraph.
type XTextParagraph struct {
	Level     int        `xml:"lvl,attr,omitempty"`
	Indent    int        `xml:"indent,attr,omitempty"`
	Alignment string     `xml:"algn,attr,omitempty"`
	TextRuns  []XTextRun `xml:"r"`
}

// XTextRun represents a text run.
type XTextRun struct {
	Text           string           `xml:"t,omitempty"`
	TextProperties *XTextProperties `xml:"rPr,omitempty"`
}

// XTextProperties holds text run properties.
type XTextProperties struct {
	FontSize  int    `xml:"sz,attr,omitempty"`
	Bold      bool   `xml:"b,attr,omitempty"`
	Italic    bool   `xml:"i,attr,omitempty"`
	Underline string `xml:"u,attr,omitempty"`
	FontFace  string `xml:"typeface,attr,omitempty"`
	Color     string `xml:"solidFill,omitempty"`
}

// XPicture represents a picture shape.
type XPicture struct {
	XMLName struct{} `xml:"pic"`

	NonVisual       XNonVisualDrawingPic `xml:"nvPicPr"`
	BlipFill        *XBlipFillProperties `xml:"blipFill,omitempty"`
	ShapeProperties *XShapeProperties    `xml:"spPr,omitempty"`
}

// XNonVisualDrawingPic holds non-visual drawing properties for a picture
// (CT_PictureNonVisual: cNvPr, cNvPicPr, nvPr).
type XNonVisualDrawingPic struct {
	CNvPr    *XNvCxnSpPr `xml:"cNvPr"`
	CNvPicPr *XNvPicPr   `xml:"cNvPicPr"`
	NvPr     XEmptyElem  `xml:"nvPr"`
}

// XNvPicPr holds non-visual picture properties.
type XNvPicPr struct {
	CNvPr *XNvPr `xml:"cNvPr,omitempty"`
}

// XBlipFillProperties holds picture fill properties.
type XBlipFillProperties struct {
	XMLName struct{}            `xml:"blipFill"`
	Blip    *XBlip              `xml:"blip,omitempty"`
	Stretch *XStretchProperties `xml:"stretch,omitempty"`
}

// XBlip holds a picture reference.
type XBlip struct {
	Embed string `xml:"rembed,attr,omitempty"`
}

// XFillProperties holds fill properties.
type XFillProperties struct {
	XMLName struct{} `xml:"fillRect"`
}

// XStretchProperties holds stretch fill properties.
type XStretchProperties struct {
	XMLName  struct{}             `xml:"stretch"`
	FillRect *XFillRectProperties `xml:"fillRect"`
}

// XFillRectProperties holds fill rectangle properties.
type XFillRectProperties struct {
}

// XGraphicFrame represents a graphic frame. Field order matches
// CT_GraphicalObjectFrame: nvGraphicFramePr, xfrm, graphic.
type XGraphicFrame struct {
	XMLName struct{} `xml:"graphicFrame"`

	NonVisual   XNonVisualGraphicFrame `xml:"nvGraphicFramePr"`
	Transform2D *XTransform2D          `xml:"xfrm,omitempty"`
	Graphic     *XGraphic              `xml:"graphic,omitempty"`
}

// XNonVisualGraphicFrame holds non-visual properties for a graphic frame
// (CT_GraphicalObjectFrameNonVisual: cNvPr, cNvGraphicFramePr, nvPr).
type XNonVisualGraphicFrame struct {
	CNvPr             *XNvCxnSpPr        `xml:"cNvPr"`
	CNvGraphicFramePr *XNvGraphicFramePr `xml:"cNvGraphicFramePr"`
	NvPr              XEmptyElem         `xml:"nvPr"`
}

// XNvGraphicFramePr holds non-visual graphic frame properties.
type XNvGraphicFramePr struct {
	CNvPr *XNvPr `xml:"cNvPr,omitempty"`
}

// XGraphic represents an <a:graphic> element.
type XGraphic struct {
	XMLName     struct{}      `xml:"graphic"`
	GraphicData *XGraphicData `xml:"graphicData,omitempty"`
}

// XGraphicData wraps the typed graphic payload (a table, in V1) with its
// schema URI.
type XGraphicData struct {
	URI   string  `xml:"uri,attr"`
	Table *XTable `xml:"tbl,omitempty"`
}

// TableGraphicDataURI is the graphicData URI for DrawingML tables.
const TableGraphicDataURI = "http://schemas.openxmlformats.org/drawingml/2006/table"

// XTableGrid represents a table grid.
type XTableGrid struct {
	XMLName  struct{}       `xml:"tblGrid"`
	GridCols []XTableColumn `xml:"gridCol"`
}

// XTable represents a table.
type XTable struct {
	XMLName struct{}    `xml:"tbl"`
	Grid    *XTableGrid `xml:"tblGrid,omitempty"`
	Rows    []XTableRow `xml:"tr"`
}

// XTableColumn represents a table column.
type XTableColumn struct {
	W int `xml:"w,attr"`
}

// XTableRow represents a table row.
type XTableRow struct {
	GridSpan int          `xml:"gridSpan,attr,omitempty"`
	Cells    []XTableCell `xml:"tc"`
}

// XTableCell represents a table cell.
type XTableCell struct {
	XMLName  struct{}   `xml:"tc"`
	GridSpan int        `xml:"gridSpan,attr,omitempty"`
	RowSpan  int        `xml:"rowSpan,attr,omitempty"`
	Vertical string     `xml:"anchor,attr,omitempty"`
	TextBody *XTextBody `xml:"txBody,omitempty"`
}
