package slide

import (
	"encoding/xml"
	"fmt"

	"github.com/hurtener/pptx-go/internal/ooxml"
	"github.com/hurtener/pptx-go/internal/ooxml/relations"
	"github.com/hurtener/pptx-go/internal/opc"
)

// NewShapeIDAllocator creates a new ID allocator.
// reservedID: the reserved starting ID; nextID begins at reservedID + 1.
func NewShapeIDAllocator(reservedID uint32) *ShapeIDAllocator {
	return &ShapeIDAllocator{
		nextID:     reservedID + 1,
		reservedID: reservedID,
		maxID:      0, // no limit
	}
}

// NewShapeIDAllocatorWithMax creates an allocator with a maximum ID limit.
func NewShapeIDAllocatorWithMax(reservedID, maxID uint32) *ShapeIDAllocator {
	return &ShapeIDAllocator{
		nextID:     reservedID + 1,
		reservedID: reservedID,
		maxID:      maxID,
	}
}

// Next allocates the next ID and returns it.
func (a *ShapeIDAllocator) Next() uint32 {
	if a.maxID > 0 && a.nextID >= a.maxID {
		return 0 // out of range
	}
	id := a.nextID
	a.nextID++
	return id
}

// NextBatch allocates count IDs in bulk and returns them (does not include reservedID).
func (a *ShapeIDAllocator) NextBatch(count int) []uint32 {
	ids := make([]uint32, count)
	for i := 0; i < count; i++ {
		ids[i] = a.Next()
	}
	return ids
}

// Peek returns the next ID that would be allocated without actually allocating it.
func (a *ShapeIDAllocator) Peek() uint32 {
	return a.nextID
}

// Current returns the most recently allocated ID.
func (a *ShapeIDAllocator) Current() uint32 {
	if a.nextID > a.reservedID+1 {
		return a.nextID - 1
	}
	return a.reservedID
}

// Reset resets the allocator to start from reservedID + 1.
func (a *ShapeIDAllocator) Reset() {
	a.nextID = a.reservedID + 1
}

// ResetFrom resets the allocator to start from startID.
func (a *ShapeIDAllocator) ResetFrom(startID uint32) {
	a.nextID = startID
}

// SetReserved sets the reserved starting ID and resets the allocator.
func (a *ShapeIDAllocator) SetReserved(reservedID uint32) {
	a.reservedID = reservedID
	a.nextID = reservedID + 1
}

// Remaining returns the number of IDs still available for allocation.
func (a *ShapeIDAllocator) Remaining() uint32 {
	if a.maxID == 0 {
		return ^uint32(0) // maximum value
	}
	return a.maxID - a.nextID + 1
}

// IsExhausted reports whether the allocator has run out of IDs.
func (a *ShapeIDAllocator) IsExhausted() bool {
	if a.maxID == 0 {
		return false
	}
	return a.nextID > a.maxID
}

// UsedCount returns the number of IDs that have been allocated.
func (a *ShapeIDAllocator) UsedCount() uint32 {
	return a.nextID - a.reservedID - 1
}

// ============================================================================
// NewShapeIDAllocatorSync creates a thread-safe ID allocator.
func NewShapeIDAllocatorSync(reservedID uint32) *ShapeIDAllocatorSync {
	return &ShapeIDAllocatorSync{
		nextID:     reservedID + 1,
		reservedID: reservedID,
	}
}

// NewShapeIDAllocatorSyncWithMax creates a thread-safe allocator with a maximum ID limit.
func NewShapeIDAllocatorSyncWithMax(reservedID, maxID uint32) *ShapeIDAllocatorSync {
	return &ShapeIDAllocatorSync{
		nextID:     reservedID + 1,
		reservedID: reservedID,
		maxID:      maxID,
	}
}

// Next allocates the next ID in a thread-safe manner.
func (a *ShapeIDAllocatorSync) Next() uint32 {
	a.mu.Lock()
	defer a.mu.Unlock()

	if a.maxID > 0 && a.nextID >= a.maxID {
		return 0
	}
	id := a.nextID
	a.nextID++
	return id
}

// NextBatch allocates count IDs in bulk in a thread-safe manner.
func (a *ShapeIDAllocatorSync) NextBatch(count int) []uint32 {
	a.mu.Lock()
	defer a.mu.Unlock()

	ids := make([]uint32, count)
	for i := 0; i < count; i++ {
		if a.maxID > 0 && a.nextID >= a.maxID {
			ids[i] = 0
			continue
		}
		ids[i] = a.nextID
		a.nextID++
	}
	return ids
}

// TryNext tries to allocate an ID; returns false if no IDs are available.
func (a *ShapeIDAllocatorSync) TryNext() (uint32, bool) {
	a.mu.Lock()
	defer a.mu.Unlock()

	if a.maxID > 0 && a.nextID >= a.maxID {
		return 0, false
	}
	id := a.nextID
	a.nextID++
	return id, true
}

// Peek returns the next ID that would be allocated, without allocating it, in a thread-safe manner.
func (a *ShapeIDAllocatorSync) Peek() uint32 {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.nextID
}

// Reset resets the allocator in a thread-safe manner.
func (a *ShapeIDAllocatorSync) Reset() {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.nextID = a.reservedID + 1
}

// ResetFrom resets the allocator to start from startID in a thread-safe manner.
func (a *ShapeIDAllocatorSync) ResetFrom(startID uint32) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.nextID = startID
}

// ============================================================================
// SlidePart ID management methods
// ============================================================================

// Allocator returns the current shape ID allocator for custom management.
// Note: a single Slide is generated by a single goroutine and is not concurrent-safe.
func (s *SlidePart) Allocator() *ShapeIDAllocator {
	return &ShapeIDAllocator{
		nextID:     s.nextShapeID,
		reservedID: 1,
	}
}

// NextShapeID returns the next available shape ID without incrementing the counter.
func (s *SlidePart) NextShapeID() uint32 {
	return s.nextShapeID
}

// AllocateShapeID allocates a new shape ID and returns it.
func (s *SlidePart) AllocateShapeID() uint32 {
	id := s.nextShapeID
	s.nextShapeID++
	return id
}

// AllocateShapeIDBatch allocates count shape IDs in bulk.
func (s *SlidePart) AllocateShapeIDBatch(count int) []uint32 {
	ids := make([]uint32, count)
	for i := 0; i < count; i++ {
		ids[i] = s.nextShapeID
		s.nextShapeID++
	}
	return ids
}

// AllocateShapeIDWithOffset allocates a shape ID offset by the given amount above the current position.
func (s *SlidePart) AllocateShapeIDWithOffset(offset uint32) uint32 {
	id := s.nextShapeID + offset
	s.nextShapeID = id + 1
	return id
}

// PeekNextShapeID returns the next available shape ID without incrementing the counter.
func (s *SlidePart) PeekNextShapeID() uint32 {
	return s.nextShapeID
}

// CurrentShapeID returns the most recently allocated shape ID.
func (s *SlidePart) CurrentShapeID() uint32 {
	if s.nextShapeID > 2 {
		return s.nextShapeID - 1
	}
	return 1
}

// ResetShapeID resets the shape ID allocator.
func (s *SlidePart) ResetShapeID() {
	s.nextShapeID = 2
}

// SetShapeIDStart sets the starting value for shape ID allocation.
func (s *SlidePart) SetShapeIDStart(startID uint32) {
	if startID < 2 {
		startID = 2
	}
	s.nextShapeID = startID
}

// ShapeIDCount returns the number of shape IDs that have been allocated.
func (s *SlidePart) ShapeIDCount() uint32 {
	return s.nextShapeID - 2
}

// NewSlidePart creates a new slide part.
func NewSlidePart(id int) *SlidePart {
	uri := opc.NewPackURI(fmt.Sprintf("/ppt/slides/slide%d.xml", id))
	return &SlidePart{
		uri:         uri,
		spTree:      NewXSpTree(),
		nextShapeID: 2, // 1 is already used by the spTree itself
		rels:        opc.NewRelationships(uri),
	}
}

// NewSlidePartWithURI creates a slide part with the specified URI.
func NewSlidePartWithURI(uri *opc.PackURI) *SlidePart {
	return &SlidePart{
		uri:         uri,
		spTree:      NewXSpTree(),
		nextShapeID: 2,
		rels:        opc.NewRelationships(uri),
	}
}

// PartURI returns the part URI.
func (s *SlidePart) PartURI() *opc.PackURI {
	return s.uri
}

// SetURI sets the part URI.
func (s *SlidePart) SetURI(uri *opc.PackURI) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.uri = uri
}

// LayoutRId returns the associated layout relationship ID.
func (s *SlidePart) LayoutRId() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.layoutRId
}

// SetLayoutRId sets the associated layout relationship ID.
func (s *SlidePart) SetLayoutRId(rId string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.layoutRId = rId
}

// MasterRId returns the associated master relationship ID.
func (s *SlidePart) MasterRId() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.masterRId
}

// SetMasterRId sets the associated master relationship ID.
func (s *SlidePart) SetMasterRId(rId string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.masterRId = rId
}

// Relationships returns the slide relationship manager (using opc.Relationships).
func (s *SlidePart) Relationships() *opc.Relationships {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.rels
}

// SpTree returns the shape tree for use by upper-layer builder operations.
func (s *SlidePart) SpTree() *XSpTree {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.spTree
}

// AppendShapeChild appends a child element to the shape tree for upper-layer builder operations.
func (s *SlidePart) AppendShapeChild(child any) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.spTree.Children = append(s.spTree.Children, child)
}

// NewXSpTree creates a new shape tree.
func NewXSpTree() *XSpTree {
	return &XSpTree{
		NonVisual: nvGrpSpPr{
			CNvPr: &XNvCxnSpPr{
				ID:   1,
				Name: "Layout",
			},
		},
		Children: make([]any, 0),
	}
}

// ToXML serializes the SlidePart to slide XML (D-032): xml.Marshal emits bare
// element names — which, unlike the retired hand-rolled writer, serializes
// attributes correctly — and ooxml.RestoreNamespaces re-applies the canonical
// p:/a:/r: prefixes and declares the used namespaces on the root.
func (s *SlidePart) ToXML() ([]byte, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	xs := XSlide{
		CSld:      &XCSld{SpTree: s.spTree},
		ClrMapOvr: &XClrMapOvr{MasterClrMapping: &XMasterClrMapping{}},
	}

	bare, err := xml.Marshal(&xs)
	if err != nil {
		return nil, fmt.Errorf("marshal slide: %w", err)
	}
	restored, err := ooxml.RestoreNamespaces(bare)
	if err != nil {
		return nil, fmt.Errorf("restore slide namespaces: %w", err)
	}
	return append([]byte(ooxml.XMLDeclaration), restored...), nil
}

// MarshalTextBody serializes a text body to namespaced <p:txBody> XML (bare
// marshal + RestoreNamespaces, D-032), with no XML declaration. It lets callers
// embed a rich text body into a hand-authored part (e.g. a notes slide) without
// reaching into the namespace machinery themselves (P3).
func MarshalTextBody(body *XTextBody) ([]byte, error) {
	bare, err := xml.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal text body: %w", err)
	}
	restored, err := ooxml.RestoreNamespaces(bare)
	if err != nil {
		return nil, fmt.Errorf("restore text body namespaces: %w", err)
	}
	return restored, nil
}

// FromXML deserializes a SlidePart from XML.
func (s *SlidePart) FromXML(data []byte) error {
	// Strip namespace prefixes for compatibility with Go's xml.Unmarshal.
	cleanData, err := ooxml.StripNamespacePrefixes(data)
	if err != nil {
		return fmt.Errorf("failed to clean XML: %w", err)
	}

	var xs XSlide
	if err := xml.Unmarshal(cleanData, &xs); err != nil {
		return fmt.Errorf("failed to unmarshal slide XML: %w", err)
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	if xs.CSld != nil && xs.CSld.SpTree != nil {
		s.spTree = xs.CSld.SpTree
	}

	return nil
}

// NewSlideLayoutPart creates a new slide layout part.
func NewSlideLayoutPart(id int) *SlideLayoutPart {
	return &SlideLayoutPart{
		uri:        opc.NewPackURI(fmt.Sprintf("/ppt/slideLayouts/slideLayout%d.xml", id)),
		spTree:     NewXSpTree(),
		layoutType: SlideLayoutBlank,
	}
}

// PartURI returns the part URI.
func (s *SlideLayoutPart) PartURI() *opc.PackURI {
	return s.uri
}

// LayoutType returns the layout type.
func (s *SlideLayoutPart) LayoutType() SlideLayoutType {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.layoutType
}

// SetLayoutType sets the layout type.
func (s *SlideLayoutPart) SetLayoutType(t SlideLayoutType) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.layoutType = t
}

// MasterRId returns the associated master relationship ID.
func (s *SlideLayoutPart) MasterRId() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.masterRId
}

// SetMasterRId sets the associated master relationship ID.
func (s *SlideLayoutPart) SetMasterRId(rId string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.masterRId = rId
}

// AddImageRel adds an image relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddImageRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check: reuse the existing rId if a relationship with the same target already exists.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	// Create a new relationship.
	rel, err := s.rels.AddNew(relations.RelTypeImage, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}

// AddMediaRel adds a media relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddMediaRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	rel, err := s.rels.AddNew(relations.RelTypeMedia, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}

// AddChartRel adds a chart relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddChartRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	rel, err := s.rels.AddNew(relations.RelTypeChart, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}

// AddTableRel adds a table relationship (with deduplication) and returns the assigned rId.
func (s *SlidePart) AddTableRel(targetURI string) string {
	s.mu.Lock()
	defer s.mu.Unlock()

	target := opc.NewPackURI(targetURI)

	// Deduplication check.
	if existing := s.rels.GetByTarget(target); existing != nil {
		return existing.RID()
	}

	rel, err := s.rels.AddNew(relations.RelTypeTable, targetURI, false)
	if err != nil {
		return ""
	}
	return rel.RID()
}
